### ISSUE TITLE
Uncaught Error: QWeb2: Template 'dhx_gantt.gantt_view' not found

### ISSUE THREAD

**Issue by ghost** [obayit/odoo_dhtmlxgantt#9]
When i load the module and clicked to view gantt button this error occured.

**Comment by obayit** [comment]
What version of Odoo are you using?
Did you refresh the page?

**Comment by ghost** [comment]
odoo v12 Community , yes i did it but still occured

**Comment by ghost** [comment]
am i doing wrong ? just load the module to addonpath and install from apps menu. any configuration need?

**Comment by obayit** [comment]
Check these files:

1. `__manifest__.py`: make sure there is this part
```
    'qweb': [
        "static/src/xml/gantt.xml",
    ],
```
2. `static/src/xml/gantt.xml`: make sure it contains this:
```
<?xml version="1.0" encoding="UTF-8"?>

<templates xml:space="preserve">

    <!-- <t t-name="dhx_gantt.gantt_action"> -->
    <t t-name="dhx_gantt.gantt_view">
        <!-- <button class="btn btn-primary">Click Me</button> -->
        <div class="o_dhx_gantt_root">
            <div class="o_dhx_gantt_header">
                <div class="">
                    <button type="button" class="btn btn-secondary o_dhx_critical_path o_dhx_button">Show Critical Path</button>
                    <button type="button" class="btn btn-secondary o_dhx_reschedule o_dhx_button">Reschedule</button>
                <!-- </div>
                <div class="" > -->
                    <button type="button" class="btn btn-secondary o_dhx_zoom_out o_dhx_button_right">Zoom Out</button>

                    <button type="button" class="btn btn-secondary o_dhx_zoom_in o_dhx_button_right">Zoom In</button>
                </div>
            </div>
            <div class="o_dhx_gantt">
            </div>
        </div>
    </t>
</templates>
```

**Comment by ghost** [comment]
they are the same, whatever i paste your code again and still no fixed. i was try another grantt module to add and occured same result "not found".
is there any blocking for "grantt" to community edition or anything else

**Comment by obayit** [comment]
No, it should work on community version normally.

**Comment by obayit** [comment]
Sorry I can't reproduce the issue.
Anyways, it looks like the client code (`javascript`) is not loading the view `dhx_gantt.gantt_view` for some reason.
I advice to uninstall the module, restart the server, and reinstall it.
Another thing to try: enable browser debugging, and see if there is any errors in the console tab.
But I can't really help you since I couldn't reproduce the issue.
